on: [push]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.3]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go get -u honnef.co/go/tools/cmd/staticcheck@latest
        go get -u golang.org/x/tools/cmd/goimports
    - name: Run staticcheck
      run: staticcheck ./...
    - name: Check code formatting
      run: test -z $(goimports -l .)
    - name: Run Test
      run: go test ./...
