on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

name: Test
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.1'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unit tests
        run: go test ./... -race